# Generated by Django 5.0.6 on 2024-05-31 03:11

import dashboard_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200, null=True)),
                ('chart_type', models.CharField(max_length=200, null=True)),
                ('sub_chart_type', models.CharField(max_length=200, null=True)),
                ('html_file_path', models.CharField(max_length=200)),
                ('data_file_path', models.CharField(blank=True, max_length=200, null=True)),
                ('project_status', models.CharField(default='Draft', max_length=20)),
                ('selected_column', models.JSONField(blank=True, null=True)),
                ('hash_code', models.CharField(default=dashboard_api.models.generate_hash_code, max_length=64, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
